export interface PaymentDetailRes{
  invoiceId: string,
  isPaid:boolean,
  activityId:string,
  bankPaymetId:string,
  paymentId:string,
  paymentExpired:string,
  activityPrice:number,
  taxAmmount:number,
  subTotal:number,
  total:number,
  discAmmount:number,
  bankName:string,
  titleActivity:string,
  accountNumber:string,
  accountName: string,
  imageActivity:string,
  startDate: string,
  endDate:string,
  codeStatus:string,
  statusName:string,
  periodDay:string,
  price:number,
  invoiceCode:string,
  ver:number
}
