export interface ActivityRes{
    activityId : string
	userId : string
	fullname : string
	createdAt : string
	title : string
	content : string
	providers : string
	typeCode : string
	typeName : string
	activityLocation : string
	imgActivityId : string
	price : number
	categoryCode : string
	categoryName : string
	startDate : Date
	endDate : Date
	isActive : boolean
	ver : number
}